In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data_raw = pd.read_csv('Chicago Health Atlas Data Download - Community areas(1).csv')

In [ ]:
data_raw.head()

,Layer,Name,GEOID,HCSDIA_2023-2024,EMP_2020-2024,HCSDCP_2023-2024,HCSPCPP_2023-2024,HCSRCP_2023-2024,HCSHCP_2023-2024,EVR_2018,CHAVQOS_2023-2024,HCSAPDP_2023-2024,HCSUMHAP_2023-2024,HCSUMHSP_2023-2024,HCSHYTP_2023-2024,INC_2020-2024,HDX_2020-2024,PCT-W_2020-2024,HCSIDQZ_2022-2024,HCSKTPB_2022-2024
0,NaN,NaN,NaN,"Adult diabetes (count of adults), 2023-2024",Employment-based health insurance (% of reside...,"Annual dental cleaning rate (% of adults), 202...","Primary care provider rate (% of adults), 2023...","Routine checkup rate (% of adults), 2023-2024","Health care satisfaction rate (% of adults), 2...",Eviction rate (% of renter-occupied households...,"Adult loneliness rate (percent of adults), 202...",Moderate or serious psychological distress rat...,Unmet mental health treatment need among moder...,Unmet mental health treatment need among serio...,"Hypertension rate (% of adults), 2023-2024","Median household income, 2020-2024","Hardship Index (score), 2020-2024","Demographics, White (Non-Hispanic) (% of resid...","Ambulatory difficulty (% of adults), 2022-2024","Self-care difficulty (% of adults), 2022-2024"
1,Community area,Rogers Park,1.0,5200.0,52.99399925826402,44.035398083,73.686966865,61.814514182,45.242719436,0.5869161573073937,44.047494927,59.213328318,59.786253011,45.54888857,29.22630899,63293.40698066556,52.924703695294006,44.90256848483232,9.172455435,NaN
2,Community area,Norwood Park,10.0,4600.0,70.98733677141776,71.976719837,88.486243956,87.643602191,52.042865074,0.4001325322955745,21.562906446,32.129379588,61.737621904,33.59452199,37.225356184,114149.65984845998,30.50422292942487,71.70275824355703,6.513854445,NaN
3,Community area,Jefferson Park,11.0,3600.0,67.19229940966909,78.957565367,77.95192877,71.996947265,54.220839187,0.5610073506358747,27.000548355,35.173310279,55.338160313,47.30423416,27.840770422,97374.54676004623,30.91804574579658,55.98983052265246,2.676950433,NaN
4,Community area,Forest Glen,12.0,1300.0,67.11980891697104,81.438358406,91.842750587,81.740413493,73.491536975,0.8898550211788571,8.7430955823,28.303037367,66.271608748,NaN,42.536637517,139311.02517710617,15.92976996167712,70.6717970991724,9.287716717,NaN

In [3]:
data_clean = data_raw.copy()
data_clean.columns = data_clean.iloc[0]
data_clean = data_clean[1:].reset_index(drop=True)
# strip whitespace
data_clean.columns = data_clean.columns.str.split('(').str[0].str.strip()

In [ ]:
data_clean.head()

,NaN,NaN,NaN,Adult diabetes,Employment-based health insurance,Annual dental cleaning rate,Primary care provider rate,Routine checkup rate,Health care satisfaction rate,Eviction rate,Adult loneliness rate,Moderate or serious psychological distress rate,Unmet mental health treatment need among moderate or serious psychological distress rate,Unmet mental health treatment need among serious psychological distress rate,Hypertension rate,"Median household income, 2020-2024",Hardship Index,"Demographics, White",Ambulatory difficulty,Self-care difficulty
0,Community area,Rogers Park,1.0,5200.0,52.99399925826402,44.035398083,73.686966865,61.814514182,45.242719436,0.5869161573073937,44.047494927,59.213328318,59.786253011,45.54888857,29.22630899,63293.40698066556,52.924703695294006,44.90256848483232,9.172455435,NaN
1,Community area,Norwood Park,10.0,4600.0,70.98733677141776,71.976719837,88.486243956,87.643602191,52.042865074,0.4001325322955745,21.562906446,32.129379588,61.737621904,33.59452199,37.225356184,114149.65984845998,30.50422292942487,71.70275824355703,6.513854445,NaN
2,Community area,Jefferson Park,11.0,3600.0,67.19229940966909,78.957565367,77.95192877,71.996947265,54.220839187,0.5610073506358747,27.000548355,35.173310279,55.338160313,47.30423416,27.840770422,97374.54676004623,30.91804574579658,55.98983052265246,2.676950433,NaN
3,Community area,Forest Glen,12.0,1300.0,67.11980891697104,81.438358406,91.842750587,81.740413493,73.491536975,0.8898550211788571,8.7430955823,28.303037367,66.271608748,NaN,42.536637517,139311.02517710617,15.92976996167712,70.6717970991724,9.287716717,NaN
4,Community area,North Park,13.0,2300.0,49.16409416508024,57.405095828,90.966624875,70.498270367,57.586817816,0.31131833767515515,30.247027564,43.538041855,81.271934216,64.69022217,45.934451848,68716.37674567565,63.755760336475554,44.949540627489824,4.714016736,NaN

In [4]:
data_clean = data_clean.rename(columns={
    'Unmet mental health treatment need among moderate or serious psychological distress rate': 'unmet mh trt mod to ser',
    'Unmet mental health treatment need among serious psychological distress rate': 'unmet mh trt mod to ser', 
    'NaN' : 'Community area'
})

In [7]:
data_clean.head()

,NaN,NaN,NaN,Adult diabetes,Employment-based health insurance,Annual dental cleaning rate,Primary care provider rate,Routine checkup rate,Health care satisfaction rate,Eviction rate,Adult loneliness rate,Moderate or serious psychological distress rate,unmet mh trt mod to ser,unmet mh trt mod to ser,Hypertension rate,"Median household income, 2020-2024",Hardship Index,"Demographics, White",Ambulatory difficulty,Self-care difficulty
0,Community area,Rogers Park,1.0,5200.0,52.99399925826402,44.035398083,73.686966865,61.814514182,45.242719436,0.5869161573073937,44.047494927,59.213328318,59.786253011,45.54888857,29.22630899,63293.40698066556,52.924703695294006,44.90256848483232,9.172455435,NaN
1,Community area,Norwood Park,10.0,4600.0,70.98733677141776,71.976719837,88.486243956,87.643602191,52.042865074,0.4001325322955745,21.562906446,32.129379588,61.737621904,33.59452199,37.225356184,114149.65984845998,30.50422292942487,71.70275824355703,6.513854445,NaN
2,Community area,Jefferson Park,11.0,3600.0,67.19229940966909,78.957565367,77.95192877,71.996947265,54.220839187,0.5610073506358747,27.000548355,35.173310279,55.338160313,47.30423416,27.840770422,97374.54676004623,30.91804574579658,55.98983052265246,2.676950433,NaN
3,Community area,Forest Glen,12.0,1300.0,67.11980891697104,81.438358406,91.842750587,81.740413493,73.491536975,0.8898550211788571,8.7430955823,28.303037367,66.271608748,NaN,42.536637517,139311.02517710617,15.92976996167712,70.6717970991724,9.287716717,NaN
4,Community area,North Park,13.0,2300.0,49.16409416508024,57.405095828,90.966624875,70.498270367,57.586817816,0.31131833767515515,30.247027564,43.538041855,81.271934216,64.69022217,45.934451848,68716.37674567565,63.755760336475554,44.949540627489824,4.714016736,NaN

In [5]:
data_clean = data_clean.drop(data_clean.columns[-1], axis = 1)
data_clean.head()

,NaN,NaN,NaN,Adult diabetes,Employment-based health insurance,Annual dental cleaning rate,Primary care provider rate,Routine checkup rate,Health care satisfaction rate,Eviction rate,Adult loneliness rate,Moderate or serious psychological distress rate,unmet mh trt mod to ser,unmet mh trt mod to ser,Hypertension rate,"Median household income, 2020-2024",Hardship Index,"Demographics, White",Ambulatory difficulty
0,Community area,Rogers Park,1.0,5200.0,52.99399925826402,44.035398083,73.686966865,61.814514182,45.242719436,0.5869161573073937,44.047494927,59.213328318,59.786253011,45.54888857,29.22630899,63293.40698066556,52.924703695294006,44.90256848483232,9.172455435
1,Community area,Norwood Park,10.0,4600.0,70.98733677141776,71.976719837,88.486243956,87.643602191,52.042865074,0.4001325322955745,21.562906446,32.129379588,61.737621904,33.59452199,37.225356184,114149.65984845998,30.50422292942487,71.70275824355703,6.513854445
2,Community area,Jefferson Park,11.0,3600.0,67.19229940966909,78.957565367,77.95192877,71.996947265,54.220839187,0.5610073506358747,27.000548355,35.173310279,55.338160313,47.30423416,27.840770422,97374.54676004623,30.91804574579658,55.98983052265246,2.676950433
3,Community area,Forest Glen,12.0,1300.0,67.11980891697104,81.438358406,91.842750587,81.740413493,73.491536975,0.8898550211788571,8.7430955823,28.303037367,66.271608748,NaN,42.536637517,139311.02517710617,15.92976996167712,70.6717970991724,9.287716717
4,Community area,North Park,13.0,2300.0,49.16409416508024,57.405095828,90.966624875,70.498270367,57.586817816,0.31131833767515515,30.247027564,43.538041855,81.271934216,64.69022217,45.934451848,68716.37674567565,63.755760336475554,44.949540627489824,4.714016736

In [6]:
chi_pop = pd.read_csv('Chi_pop.csv')
chi_pop.head()

            Layer            Name  GEOID                      POP_2020-2024
0             NaN             NaN    NaN  Population (residents), 2020-2024
1  Community area     Rogers Park    1.0                        54023.51405
2  Community area    Norwood Park   10.0                        42638.43086
3  Community area  Jefferson Park   11.0                        26634.54233
4  Community area     Forest Glen   12.0                        19886.37507

In [7]:
pop_clean = chi_pop.copy()
pop_clean.columns = pop_clean.iloc[0]
pop_clean = pop_clean[1:].reset_index(drop=True)
# strip whitespace
pop_clean.columns = pop_clean.columns.str.split('(').str[0].str.strip()

In [ ]:
pop_clean.head()

0             NaN             NaN   NaN   Population
0  Community area     Rogers Park   1.0  54023.51405
1  Community area    Norwood Park  10.0  42638.43086
2  Community area  Jefferson Park  11.0  26634.54233
3  Community area     Forest Glen  12.0  19886.37507
4  Community area      North Park  13.0  18307.61022

In [8]:
data_clean['population'] = pop_clean['Population']
data_clean.head()

,NaN,NaN,NaN,Adult diabetes,Employment-based health insurance,Annual dental cleaning rate,Primary care provider rate,Routine checkup rate,Health care satisfaction rate,Eviction rate,Adult loneliness rate,Moderate or serious psychological distress rate,unmet mh trt mod to ser,unmet mh trt mod to ser,Hypertension rate,"Median household income, 2020-2024",Hardship Index,"Demographics, White",Ambulatory difficulty,population
0,Community area,Rogers Park,1.0,5200.0,52.99399925826402,44.035398083,73.686966865,61.814514182,45.242719436,0.5869161573073937,44.047494927,59.213328318,59.786253011,45.54888857,29.22630899,63293.40698066556,52.924703695294006,44.90256848483232,9.172455435,54023.51405
1,Community area,Norwood Park,10.0,4600.0,70.98733677141776,71.976719837,88.486243956,87.643602191,52.042865074,0.4001325322955745,21.562906446,32.129379588,61.737621904,33.59452199,37.225356184,114149.65984845998,30.50422292942487,71.70275824355703,6.513854445,42638.43086
2,Community area,Jefferson Park,11.0,3600.0,67.19229940966909,78.957565367,77.95192877,71.996947265,54.220839187,0.5610073506358747,27.000548355,35.173310279,55.338160313,47.30423416,27.840770422,97374.54676004623,30.91804574579658,55.98983052265246,2.676950433,26634.54233
3,Community area,Forest Glen,12.0,1300.0,67.11980891697104,81.438358406,91.842750587,81.740413493,73.491536975,0.8898550211788571,8.7430955823,28.303037367,66.271608748,NaN,42.536637517,139311.02517710617,15.92976996167712,70.6717970991724,9.287716717,19886.37507
4,Community area,North Park,13.0,2300.0,49.16409416508024,57.405095828,90.966624875,70.498270367,57.586817816,0.31131833767515515,30.247027564,43.538041855,81.271934216,64.69022217,45.934451848,68716.37674567565,63.755760336475554,44.949540627489824,4.714016736,18307.61022

In [9]:
data_clean['Adult diabetes'] = pd.to_numeric(data_clean['Adult diabetes'], errors='coerce')
data_clean['population'] = pd.to_numeric(data_clean['population'], errors='coerce')

data_clean['diabetes ratio'] = (
    data_clean['Adult diabetes'] / data_clean['population']
)
data_clean.head()

,NaN,NaN,NaN,Adult diabetes,Employment-based health insurance,Annual dental cleaning rate,Primary care provider rate,Routine checkup rate,Health care satisfaction rate,Eviction rate,...,Moderate or serious psychological distress rate,unmet mh trt mod to ser,unmet mh trt mod to ser,Hypertension rate,"Median household income, 2020-2024",Hardship Index,"Demographics, White",Ambulatory difficulty,population,diabetes ratio
0,Community area,Rogers Park,1.0,5200.0,52.99399925826402,44.035398083,73.686966865,61.814514182,45.242719436,0.5869161573073937,...,59.213328318,59.786253011,45.54888857,29.22630899,63293.40698066556,52.924703695294006,44.90256848483232,9.172455435,54023.51405,0.096254
1,Community area,Norwood Park,10.0,4600.0,70.98733677141776,71.976719837,88.486243956,87.643602191,52.042865074,0.4001325322955745,...,32.129379588,61.737621904,33.59452199,37.225356184,114149.65984845998,30.50422292942487,71.70275824355703,6.513854445,42638.43086,0.107884
2,Community area,Jefferson Park,11.0,3600.0,67.19229940966909,78.957565367,77.95192877,71.996947265,54.220839187,0.5610073506358747,...,35.173310279,55.338160313,47.30423416,27.840770422,97374.54676004623,30.91804574579658,55.98983052265246,2.676950433,26634.54233,0.135163
3,Community area,Forest Glen,12.0,1300.0,67.11980891697104,81.438358406,91.842750587,81.740413493,73.491536975,0.8898550211788571,...,28.303037367,66.271608748,NaN,42.536637517,139311.02517710617,15.92976996167712,70.6717970991724,9.287716717,19886.37507,0.065371
4,Community area,North Park,13.0,2300.0,49.16409416508024,57.405095828,90.966624875,70.498270367,57.586817816,0.31131833767515515,...,43.538041855,81.271934216,64.69022217,45.934451848,68716.37674567565,63.755760336475554,44.949540627489824,4.714016736,18307.61022,0.125631

In [10]:
data_clean = data_clean.dropna(axis = 0, subset = 'Adult diabetes')

In [11]:
data_clean = data_clean.iloc[:, 3:]

In [12]:
data_clean.head()

,Adult diabetes,Employment-based health insurance,Annual dental cleaning rate,Primary care provider rate,Routine checkup rate,Health care satisfaction rate,Eviction rate,Adult loneliness rate,Moderate or serious psychological distress rate,unmet mh trt mod to ser,unmet mh trt mod to ser,Hypertension rate,"Median household income, 2020-2024",Hardship Index,"Demographics, White",Ambulatory difficulty,population,diabetes ratio
0,5200.0,52.99399925826402,44.035398083,73.686966865,61.814514182,45.242719436,0.5869161573073937,44.047494927,59.213328318,59.786253011,45.54888857,29.22630899,63293.40698066556,52.924703695294006,44.90256848483232,9.172455435,54023.51405,0.096254
1,4600.0,70.98733677141776,71.976719837,88.486243956,87.643602191,52.042865074,0.4001325322955745,21.562906446,32.129379588,61.737621904,33.59452199,37.225356184,114149.65984845998,30.50422292942487,71.70275824355703,6.513854445,42638.43086,0.107884
2,3600.0,67.19229940966909,78.957565367,77.95192877,71.996947265,54.220839187,0.5610073506358747,27.000548355,35.173310279,55.338160313,47.30423416,27.840770422,97374.54676004623,30.91804574579658,55.98983052265246,2.676950433,26634.54233,0.135163
3,1300.0,67.11980891697104,81.438358406,91.842750587,81.740413493,73.491536975,0.8898550211788571,8.7430955823,28.303037367,66.271608748,NaN,42.536637517,139311.02517710617,15.92976996167712,70.6717970991724,9.287716717,19886.37507,0.065371
4,2300.0,49.16409416508024,57.405095828,90.966624875,70.498270367,57.586817816,0.31131833767515515,30.247027564,43.538041855,81.271934216,64.69022217,45.934451848,68716.37674567565,63.755760336475554,44.949540627489824,4.714016736,18307.61022,0.125631

In [ ]:
data_clean = data_clea

In [13]:
data_clean.isna().sum()

0
Adult diabetes                                     0
Employment-based health insurance                  0
Annual dental cleaning rate                        0
Primary care provider rate                         0
Routine checkup rate                               0
Health care satisfaction rate                      0
Eviction rate                                      0
Adult loneliness rate                              0
Moderate or serious psychological distress rate    0
unmet mh trt mod to ser                            0
unmet mh trt mod to ser                            9
Hypertension rate                                  0
Median household income, 2020-2024                 0
Hardship Index                                     0
Demographics, White                                0
Ambulatory difficulty                              0
population                                         0
diabetes ratio                                     0
dtype: int64

In [14]:
data_clean.to_csv('data_clean.csv', index=False)